### ISSUE TITLE
on readme.md, need change .github directory to .git

### ISSUE THREAD

**Issue by vxyagr** [dfinity/ic-eth-starter#71] opened 2024-02-11 07:13 UTC
problem : when following instructions to run the ic-eth-starter, stopped at "prepare" step, due to problem : husky cannot find ".git" directory
solution : rename the ".github" directory to ".git"

**Comment by rvanasa** [comment] 2024-02-11 17:55
Thanks for reaching out about this. Running the `npx degit` command in the readme should create a `.git` directory, but it seems like this didn't happen in your case for some reason. The `.git` and `.github` directories are fundamentally different from each other, so the cleanest solution is to run `git init` to create a new `.git` directory. 

Closing as a duplicate of https://github.com/typicode/husky/issues/851, which is the root cause of this issue. I'd be happy to reopen if that would be helpful for anyone running into a similar issue.

**Closed by rvanasa** 2024-02-11 17:55 UTC
